// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Romp.BuildingBlocks.Domain;
using Romp.Modules.Catalog.Infrastructure;
using Romp.Modules.Catalog.Infrastructure.Persistence;
using System;

#nullable disable

namespace Romp.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CTLG")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.Style", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("AgeBracketId")
                        .HasColumnType("smallint")
                        .HasColumnName("AGE_BRKT_ID");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("CATG_ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("STYL_CODE");

                    b.Property<string>("CollectionName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("COLN_NAME");

                    b.Property<short>("FabricId")
                        .HasColumnType("smallint")
                        .HasColumnName("FBRC_ID");

                    b.Property<short>("GenderId")
                        .HasColumnType("smallint")
                        .HasColumnName("GNDR_ID");

                    b.Property<string>("InsrBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("INSR_BY");

                    b.Property<DateTimeOffset>("InsrDte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("INSR_DTE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("STYL_NAME");

                    b.Property<decimal>("TargetRetailPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("TGT_RTL_PRIC_AMT");

                    b.Property<decimal>("TargetUnitCost")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("TGT_UNIT_COST_AMT");

                    b.Property<string>("UpdtBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("UPDT_BY");

                    b.Property<DateTimeOffset?>("UpdtDte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDT_DTE");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AgeBracketId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FabricId");

                    b.HasIndex("GenderId");

                    b.ToTable("STYL_MAIN", "CTLG");
                });

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.StyleColourway", b =>
                {
                    b.Property<long>("StyleId")
                        .HasColumnType("bigint")
                        .HasColumnName("STYL_ID");

                    b.Property<short>("ColourId")
                        .HasColumnType("smallint")
                        .HasColumnName("CLR_ID");

                    b.HasKey("StyleId", "ColourId");

                    b.HasIndex("ColourId");

                    b.ToTable("STYL_CLR_MAP", "CTLG");
                });

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.StyleSize", b =>
                {
                    b.Property<long>("StyleId")
                        .HasColumnType("bigint")
                        .HasColumnName("STYL_ID");

                    b.Property<short>("SizeId")
                        .HasColumnType("smallint")
                        .HasColumnName("SIZE_ID");

                    b.HasKey("StyleId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("STYL_SIZE_MAP", "CTLG");
                });

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.StyleTargetLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("ColourId")
                        .HasColumnType("smallint")
                        .HasColumnName("CLR_ID");

                    b.Property<string>("InsrBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("INSR_BY");

                    b.Property<DateTimeOffset>("InsrDte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("INSR_DTE");

                    b.Property<short>("SizeId")
                        .HasColumnType("smallint")
                        .HasColumnName("SIZE_ID");

                    b.Property<long>("StyleId")
                        .HasColumnType("bigint")
                        .HasColumnName("STYL_ID");

                    b.Property<int>("TargetQty")
                        .HasColumnType("integer")
                        .HasColumnName("TGT_QTY");

                    b.Property<string>("UpdtBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("UPDT_BY");

                    b.Property<DateTimeOffset?>("UpdtDte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UPDT_DTE");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StyleId", "SizeId", "ColourId")
                        .IsUnique();

                    b.ToTable("STYL_TGT_LINE", "CTLG");
                });

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.StyleColourway", b =>
                {
                    b.HasOne("Romp.Modules.Catalog.Domain.Styles.Style", null)
                        .WithMany("Colourways")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_STYL_CLR_MAP_STYL_ID");
                });

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.StyleSize", b =>
                {
                    b.HasOne("Romp.Modules.Catalog.Domain.Styles.Style", null)
                        .WithMany("Sizes")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_STYL_SIZE_MAP_STYL_ID");
                });

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.StyleTargetLine", b =>
                {
                    b.HasOne("Romp.Modules.Catalog.Domain.Styles.Style", null)
                        .WithMany("TargetLines")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_STYL_TGT_LINE_STYL_ID");
                });

            modelBuilder.Entity("Romp.Modules.Catalog.Domain.Styles.Style", b =>
                {
                    b.Navigation("Colourways");

                    b.Navigation("Sizes");

                    b.Navigation("TargetLines");
                });
#pragma warning restore 612, 618
        }
    }
}
