version: 2
updates:
  - package-ecosystem: nuget
    directory: /src/api
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /src/web
    schedule:
      interval: weekly
    groups:
      angular:
        patterns: ["@angular/*", "@angular-devkit/*"]
  - package-ecosystem: docker
    directories: ["/src/api/src/Romp.Api", "/src/web"]
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
