// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Romp.Modules.Reference.Infrastructure;

#nullable disable

namespace Romp.Modules.Reference.Infrastructure.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    partial class ReferenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("REF")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Romp.Modules.Reference.Domain.AgeBracketLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AGE_BRKT_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "NEWBORN",
                            IsActive = true,
                            Name = "Newborn (0-3M)",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "INFANT",
                            IsActive = true,
                            Name = "Infant (3-12M)",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "TODDLER",
                            IsActive = true,
                            Name = "Toddler (1-3Y)",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "KIDS",
                            IsActive = true,
                            Name = "Kids (4-8Y)",
                            SortSeq = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "TWEEN",
                            IsActive = true,
                            Name = "Tween (9-12Y)",
                            SortSeq = (short)5
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.CategoryLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short?>("ParentCategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("PRNT_CATG_ID");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("CATG_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "TOPS",
                            IsActive = true,
                            Name = "Tops",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "BOTTOMS",
                            IsActive = true,
                            Name = "Bottoms",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "DRESSES",
                            IsActive = true,
                            Name = "Dresses",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "OUTERWEAR",
                            IsActive = true,
                            Name = "Outerwear",
                            SortSeq = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "SLEEPWEAR",
                            IsActive = true,
                            Name = "Sleepwear",
                            SortSeq = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "ACCESSORIES",
                            IsActive = true,
                            Name = "Accessories",
                            SortSeq = (short)6
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.CityLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CITY_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "KHI",
                            IsActive = true,
                            Name = "Karachi",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "LHE",
                            IsActive = true,
                            Name = "Lahore",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "ISB",
                            IsActive = true,
                            Name = "Islamabad",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "FSD",
                            IsActive = true,
                            Name = "Faisalabad",
                            SortSeq = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "RWP",
                            IsActive = true,
                            Name = "Rawalpindi",
                            SortSeq = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "MUX",
                            IsActive = true,
                            Name = "Multan",
                            SortSeq = (short)6
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "SKT",
                            IsActive = true,
                            Name = "Sialkot",
                            SortSeq = (short)7
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.ColourLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CLR_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "WHT",
                            IsActive = true,
                            Name = "White",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "BLK",
                            IsActive = true,
                            Name = "Black",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "RED",
                            IsActive = true,
                            Name = "Red",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "PNK",
                            IsActive = true,
                            Name = "Pink",
                            SortSeq = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "BLU",
                            IsActive = true,
                            Name = "Blue",
                            SortSeq = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "NVY",
                            IsActive = true,
                            Name = "Navy",
                            SortSeq = (short)6
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "YLW",
                            IsActive = true,
                            Name = "Yellow",
                            SortSeq = (short)7
                        },
                        new
                        {
                            Id = (short)8,
                            Code = "GRN",
                            IsActive = true,
                            Name = "Green",
                            SortSeq = (short)8
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.FabricLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FBRC_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "COTTON",
                            IsActive = true,
                            Name = "Cotton",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "DENIM",
                            IsActive = true,
                            Name = "Denim",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "FLEECE",
                            IsActive = true,
                            Name = "Fleece",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "JERSEY",
                            IsActive = true,
                            Name = "Jersey",
                            SortSeq = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "LINEN",
                            IsActive = true,
                            Name = "Linen",
                            SortSeq = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "POLY",
                            IsActive = true,
                            Name = "Polyester",
                            SortSeq = (short)6
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.GenderLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GNDR_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "BOYS",
                            IsActive = true,
                            Name = "Boys",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "GIRLS",
                            IsActive = true,
                            Name = "Girls",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "UNISEX",
                            IsActive = true,
                            Name = "Unisex",
                            SortSeq = (short)3
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.PaymentTermLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<decimal>("DefaultAdvancePercent")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("DFLT_ADV_PCT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PAYM_TERM_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "ADV100",
                            DefaultAdvancePercent = 100m,
                            IsActive = true,
                            Name = "100% Advance",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "NET50_50",
                            DefaultAdvancePercent = 50m,
                            IsActive = true,
                            Name = "50% Advance / 50% on Delivery",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "NET30_70",
                            DefaultAdvancePercent = 30m,
                            IsActive = true,
                            Name = "30% Advance / 70% on Delivery",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "NET30",
                            DefaultAdvancePercent = 0m,
                            IsActive = true,
                            Name = "Net 30 (no advance)",
                            SortSeq = (short)4
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.PoCancelReasonLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PO_CNCL_RSN_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "VendorDeclined",
                            IsActive = true,
                            Name = "Vendor Declined",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "CostDispute",
                            IsActive = true,
                            Name = "Cost Dispute",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "QualityConcern",
                            IsActive = true,
                            Name = "Quality Concern",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "StyleDiscontinued",
                            IsActive = true,
                            Name = "Style Discontinued",
                            SortSeq = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "DuplicateEntry",
                            IsActive = true,
                            Name = "Duplicate Entry",
                            SortSeq = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "Other",
                            IsActive = true,
                            Name = "Other",
                            SortSeq = (short)6
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.PoStatusLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PO_STS_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "Draft",
                            IsActive = true,
                            Name = "Draft",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "SentToVendor",
                            IsActive = true,
                            Name = "Sent to Vendor",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "Acknowledged",
                            IsActive = true,
                            Name = "Acknowledged",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "Cancelled",
                            IsActive = true,
                            Name = "Cancelled",
                            SortSeq = (short)4
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.SizeLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SIZE_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "0-3M",
                            IsActive = true,
                            Name = "0-3 Months",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "3-6M",
                            IsActive = true,
                            Name = "3-6 Months",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "6-12M",
                            IsActive = true,
                            Name = "6-12 Months",
                            SortSeq = (short)3
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "1-2Y",
                            IsActive = true,
                            Name = "1-2 Years",
                            SortSeq = (short)4
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "2-3Y",
                            IsActive = true,
                            Name = "2-3 Years",
                            SortSeq = (short)5
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "3-4Y",
                            IsActive = true,
                            Name = "3-4 Years",
                            SortSeq = (short)6
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "4-5Y",
                            IsActive = true,
                            Name = "4-5 Years",
                            SortSeq = (short)7
                        },
                        new
                        {
                            Id = (short)8,
                            Code = "5-6Y",
                            IsActive = true,
                            Name = "5-6 Years",
                            SortSeq = (short)8
                        },
                        new
                        {
                            Id = (short)9,
                            Code = "6-7Y",
                            IsActive = true,
                            Name = "6-7 Years",
                            SortSeq = (short)9
                        },
                        new
                        {
                            Id = (short)10,
                            Code = "7-8Y",
                            IsActive = true,
                            Name = "7-8 Years",
                            SortSeq = (short)10
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.VendorSpecialisationLookup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("CODE");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("DSCR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("ACT_IND");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NAME");

                    b.Property<short>("SortSeq")
                        .HasColumnType("smallint")
                        .HasColumnName("SORT_SEQ");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VNDR_SPCL_LKP", "REF");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "KNITS",
                            IsActive = true,
                            Name = "Knits",
                            SortSeq = (short)1
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "WOVENS",
                            IsActive = true,
                            Name = "Wovens",
                            SortSeq = (short)2
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "UNIFORMS",
                            IsActive = true,
                            Name = "Uniforms",
                            SortSeq = (short)3
                        });
                });

            modelBuilder.Entity("Romp.Modules.Reference.Domain.CategoryLookup", b =>
                {
                    b.HasOne("Romp.Modules.Reference.Domain.CategoryLookup", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CATG_LKP_PRNT_CATG_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
